# Generated by Django 5.1.4 on 2024-12-20 04:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_resident_options_alter_resident_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 11 digits.', regex='^\\d{11}$')]),
        ),
    ]
