# Generated by Django 5.1.4 on 2024-12-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_resident_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('generic_name', models.TextField(blank=True)),
                ('dosage', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
