# Generated by Django 5.1.4 on 2024-12-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(blank=True),
        ),
    ]
