# Generated by Django 5.1.4 on 2024-12-23 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_medicine_options_medicinerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildVaccineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit', models.PositiveIntegerField()),
                ('vaccine_name', models.CharField(max_length=50)),
                ('health_worker', models.CharField(max_length=50)),
                ('date_given', models.DateField()),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.resident')),
            ],
            options={
                'ordering': ['resident'],
            },
        ),
    ]
