# Generated by Django 5.1.4 on 2024-12-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_childvaccinehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childvaccinehistory',
            name='date_given',
            field=models.DateField(auto_now_add=True),
        ),
    ]
