# Generated by Django 5.1.4 on 2024-12-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_rename_visit_childvaccinehistory_visit_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childvaccinehistory',
            name='vaccine_name',
            field=models.TextField(max_length=100),
        ),
    ]
