# Generated by Django 5.1.4 on 2025-01-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_documentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='document_name',
            field=models.TextField(choices=[('doc1', 'doc1'), ('doc2', 'doc2')], max_length=50),
        ),
    ]
