# Generated by Django 5.1.4 on 2025-01-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_documentrequest_document_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentrequest',
            options={'ordering': ['-request_date']},
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='purpose',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
