# Generated by Django 5.1.4 on 2025-01-04 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childvaccinehistory',
            name='health_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.staff'),
        ),
    ]
