# Generated by Django 5.1.4 on 2025-01-04 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_childvaccinehistory_health_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childvaccinehistory',
            name='health_worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.staff'),
        ),
    ]
