# Generated by Django 5.1.4 on 2025-01-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_childvaccinehistory_health_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='status',
            field=models.CharField(choices=[('None', 'None'), ('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('PWD', 'PWD'), ('OFW', 'OFW'), ('Solo Parent', 'Solo Parent'), ('Out of School Youth', 'Out of School Youth'), ('Out of School Children', 'Out of School Children'), ('Indigenous Person', 'Indigenous Person')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='document_name',
            field=models.TextField(choices=[('Indigency', 'Indigency')], max_length=50),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='purpose',
            field=models.TextField(blank=True, choices=[('Employment', 'Employment'), ('Government', 'Government'), ('Identification', 'Identification'), ('Personal', 'Personal'), ('School', 'School')], max_length=100),
        ),
    ]
