# Generated by Django 5.1.4 on 2025-01-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_childvaccinehistory_health_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='document_name',
            field=models.TextField(choices=[('Indigency', 'Indigency'), ('doc2', 'doc2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='purpose',
            field=models.TextField(blank=True, choices=[('Employment', 'Employment'), ('Government', 'Government'), ('Identification', 'Identification'), ('Personal', 'Personal'), ('School', 'School')], max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(max_length=50),
        ),
    ]
