# Generated by Django 5.1.4 on 2025-01-22 03:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_remove_documentrequest_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='type',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Vial', 'Vial'), ('Syrup', 'Syrup'), ('Ointment', 'Ointment'), ('Cream', 'Cream'), ('Drops', 'Drops')], max_length=50),
        ),
    ]
